#mqtt:
#  host: tcp://192.168.100.35:8080
#  clientId: client_${random.value}
#  topic: test/system/module/biz
#  qoslevel: 1
#  username: guest
#  password: guest
#  timeout: 10000
#  keepalive: 20


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
